### ISSUE TITLE
Want to get in contact with Alistair

### ISSUE THREAD

**Issue by johnmurtari** [alistairmgreen/jsigc#20]
Alistair,
Sorry for using this out of scope, but I just didn't know how to contact you.  I love the webbased ICG log viewer.  I'm the webmaster for https://SoaringTools.org/ -- would love to host your stuff, add you as a contributor to the site?

My direct email:  jmurtari --at-- SoaringTools.org

**Comment by alistairmgreen** [comment]
I emailed him. IGC viewer is now listed on SoaringTools.org.
